[package]
name = "reywen_http"
version = "0.1.2b"
edition = "2021"
license = "GPL-3.0-only"
description = "A simple and easy to use HTTPv2 library for Rust (based on tokio/reqwest) "

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.14.26"
hyper-rustls = "0.24.0"
hyper-timeout = "0.4.1"
hyper-tls = "0.5.0"
reqwest = { version = "0.11.17", features = ["native-tls", "json"] }
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.0", features = ["full"] }
