[package]
name = "reywen_http"
version = "0.1.11"
edition = "2021"
license = "GPL-3.0-only"
description = "A simple and easy to use HTTPv2 library for Rust (based on tokio/reqwest) "

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

hyper = "0.14.27"
hyper-rustls = "0.24.0"
hyper-timeout = "0.4.1"
hyper-tls = "0.5.0"
main = "0.1.0"
tokio = "1.29.1"

# feature
serde = { version = "1.0.162", optional = true, features = ["derive"] }
serde_json = {version = "1.0.96", optional = true}


[features]
serde = ["dep:serde", "dep:serde_json"]
